# Generated by Django 5.0.4 on 2024-06-05 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_order_cartitem_created_at_alter_message_phone_number_and_more'),
        ('profiles', '0002_alter_profile_options_profile_location_profile_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Name of a customer')),
                ('phone_number', models.IntegerField(verbose_name='Phone number of a customer')),
                ('email', models.CharField(max_length=250, verbose_name='E-mail of a customer')),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('credit_card', 'Credit card')], default='credit_card', max_length=100, verbose_name='Payment method of a customer')),
                ('address', models.CharField(max_length=250, verbose_name='Address of a customer')),
                ('city', models.CharField(max_length=250, verbose_name='City where a customer lives')),
                ('country', models.CharField(max_length=250, verbose_name='Country where a customer lives')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Create at')),
            ],
            options={
                'verbose_name': 'Checkout',
            },
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(default='', max_length=150, verbose_name='Location of the user'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(default='', max_length=150, verbose_name='Phone number of the user'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'New'), ('accepted', 'Accepted'), ('pending', 'Pending'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='new', max_length=100, verbose_name='Status of a customer')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Time of delivery')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.profile', verbose_name='Customer')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True, verbose_name='quantity')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_checkout', to='profiles.order', verbose_name='order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'cart item',
                'verbose_name_plural': 'cart items',
            },
        ),
    ]
