# Generated by Django 5.0.2 on 2024-06-05 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_checkout_alter_profile_location_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Checkout',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.order', verbose_name='order'),
        ),
    ]
