# Generated by Django 5.0.4 on 2024-06-06 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_orderproduct_order_alter_order_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
    ]
