# Generated by Django 5.0.4 on 2024-06-06 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_remove_order_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orders',
            field=models.ManyToManyField(related_name='orders', to='profiles.orderproduct', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(default='no location', max_length=150, verbose_name='Location of the user'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(default='no name', max_length=150, verbose_name='Name of the user'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(default='no phone number', max_length=150, verbose_name='Phone number of the user'),
        ),
    ]
