# Generated by Django 5.0.4 on 2024-06-06 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_order_orders_alter_profile_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='orders',
        ),
    ]
