# Generated by Django 5.0.4 on 2024-06-03 17:18

import django.db.models.deletion
import profiles.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Name of a customer')),
                ('phone_number', models.IntegerField(verbose_name='Phone number of a customer')),
                ('email', models.CharField(max_length=250, verbose_name='E-mail of a customer')),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('credit_card', 'Credit card')], default='credit_card', max_length=100, verbose_name='Payment method of a customer')),
                ('address', models.CharField(max_length=250, verbose_name='Address of a customer')),
                ('city', models.CharField(max_length=250, verbose_name='City where a customer lives')),
                ('country', models.CharField(max_length=250, verbose_name='Country where a customer lives')),
                ('status', models.CharField(choices=[('new', 'New'), ('accepted', 'Accepted'), ('pending', 'Pending'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='new', max_length=100, verbose_name='Status of a customer')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Time of delivery')),
            ],
            options={
                'verbose_name': 'Checkout',
            },
        ),
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='promo/', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Promo',
                'verbose_name_plural': 'Promos',
            },
        ),
        migrations.CreateModel(
            name='StandardSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_rights_reserved', models.CharField(max_length=300, verbose_name='All rights reserved')),
                ('main_email', models.CharField(max_length=150, verbose_name='Main email')),
                ('main_phone_number', models.CharField(max_length=100, verbose_name='Main Phone Number')),
            ],
            options={
                'verbose_name': 'Standard settings',
            },
        ),
        migrations.CreateModel(
            name='WorkingDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='working day', max_length=50, verbose_name='Title')),
            ],
            options={
                'verbose_name': 'Working hours',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('answered', 'Answered')], default='sent', max_length=50, verbose_name='Status of a message')),
                ('phone_number', models.CharField(max_length=20, validators=[profiles.utils.phone_number_validation], verbose_name='Phone number')),
                ('text', models.TextField(verbose_name='Text')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_author', to=settings.AUTH_USER_MODEL, verbose_name='Author of the message')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
                ('quantity', models.IntegerField(default=1, verbose_name='Quantity')),
                ('main_pic', models.ImageField(blank=True, null=True, upload_to='product_images/', verbose_name='Main product picture')),
                ('pic_2', models.ImageField(blank=True, null=True, upload_to='product_images/', verbose_name='Second product picture')),
                ('pic_3', models.ImageField(blank=True, null=True, upload_to='product_images/', verbose_name='Third product picture')),
                ('pic_4', models.ImageField(blank=True, null=True, upload_to='product_images/', verbose_name='Fourth product picture')),
                ('price', models.FloatField(verbose_name='Product price')),
                ('discount', models.FloatField(default=0, verbose_name='Product discount')),
                ('shipping_fee', models.FloatField(default=0, verbose_name='Product shipping fee')),
                ('in_stock', models.BooleanField(default=True, verbose_name='In stock?')),
                ('is_popular', models.BooleanField(default=False, verbose_name='Is popular?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Product created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Product updated at')),
                ('description', models.TextField(verbose_name='Description')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_category', to='market.category', verbose_name='Product category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='WorkingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=50, verbose_name='Day')),
                ('start', models.CharField(max_length=30, verbose_name='Start hour')),
                ('finish', models.CharField(max_length=30, verbose_name='Finish hour')),
                ('working_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.workingday')),
            ],
            options={
                'verbose_name': 'Working hours',
            },
        ),
    ]
