# Generated by Django 5.0.4 on 2024-06-05 16:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_cartitem_checkout_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Name of a customer')),
                ('phone_number', models.IntegerField(verbose_name='Phone number of a customer')),
                ('email', models.CharField(max_length=250, verbose_name='E-mail of a customer')),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('credit_card', 'Credit card')], default='credit_card', max_length=100, verbose_name='Payment method of a customer')),
                ('address', models.CharField(max_length=250, verbose_name='Address of a customer')),
                ('city', models.CharField(max_length=250, verbose_name='City where a customer lives')),
                ('country', models.CharField(max_length=250, verbose_name='Country where a customer lives')),
                ('status', models.CharField(choices=[('new', 'New'), ('accepted', 'Accepted'), ('pending', 'Pending'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='new', max_length=100, verbose_name='Status of a customer')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Time of delivery')),
            ],
            options={
                'verbose_name': 'Checkout',
            },
        ),
        migrations.AddField(
            model_name='cartitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created_at'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='phone_number',
            field=models.CharField(max_length=20, verbose_name='Phone number'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_checkout', to='market.order', verbose_name='order'),
        ),
        migrations.DeleteModel(
            name='Checkout',
        ),
    ]
