# Generated by Django 5.0.2 on 2024-06-05 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_order_cartitem_created_at_alter_message_phone_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Name of a customer')),
                ('phone_number', models.IntegerField(verbose_name='Phone number of a customer')),
                ('email', models.CharField(max_length=250, verbose_name='E-mail of a customer')),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('credit_card', 'Credit card')], default='credit_card', max_length=100, verbose_name='Payment method of a customer')),
                ('address', models.CharField(max_length=250, verbose_name='Address of a customer')),
                ('city', models.CharField(max_length=250, verbose_name='City where a customer lives')),
                ('country', models.CharField(max_length=250, verbose_name='Country where a customer lives')),
                ('status', models.CharField(choices=[('new', 'New'), ('accepted', 'Accepted'), ('pending', 'Pending'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='new', max_length=100, verbose_name='Status of a customer')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Time of delivery')),
            ],
            options={
                'verbose_name': 'Checkout',
            },
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
