# Generated by Django 5.0.4 on 2024-06-06 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_checkout_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='order',
        ),
        migrations.AlterField(
            model_name='checkout',
            name='payment_method',
            field=models.CharField(choices=[('credit_card', 'Credit card')], default='credit_card', max_length=100, verbose_name='Payment method of a customer'),
        ),
    ]
