# Generated by Django 5.0.4 on 2024-06-06 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_remove_checkout_order_alter_checkout_payment_method'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ordered_By', to=settings.AUTH_USER_MODEL, verbose_name='Ordered by'),
            preserve_default=False,
        ),
    ]
