# Generated by Django 5.0.4 on 2024-06-06 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0010_alter_checkout_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='BigFeaturedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='market.product', verbose_name='Big featured product')),
            ],
        ),
        migrations.CreateModel(
            name='SmallFeaturedProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='market.product', verbose_name='Big featured product')),
            ],
        ),
    ]
