# Generated by Django 5.0.4 on 2024-06-06 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0011_bigfeaturedproduct_smallfeaturedproducts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='logo/', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Logo',
                'verbose_name_plural': 'Logos',
            },
        ),
        migrations.AlterModelOptions(
            name='bigfeaturedproduct',
            options={'verbose_name': 'Big featured product', 'verbose_name_plural': 'Big featured products'},
        ),
        migrations.AlterModelOptions(
            name='smallfeaturedproducts',
            options={'verbose_name': 'Small featured product', 'verbose_name_plural': 'Small featured products'},
        ),
    ]
